import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const storyFiles = [
  '../foundations/DesignSystemProvider.stories.tsx',
  '../components/Controls.stories.tsx',
  '../components/Iconography.stories.tsx',
  '../components/Overlays.stories.tsx',
  '../components/Navigation.stories.tsx',
  '../components/Display.stories.tsx',
  '../objects/PropertyValue.stories.tsx',
  '../objects/PropertyPanel.stories.tsx',
  '../objects/ObjectHeader.stories.tsx',
  '../workbench/DataGrid.stories.tsx',
  '../objects/Links.stories.tsx',
  '../components/Search.stories.tsx',
  '../components/Status.stories.tsx',
  '../workbench/Shell.stories.tsx',
  '../objects/Explore.stories.tsx',
  '../workbench/Workbench.stories.tsx',
  '../workbench/Compositions.stories.tsx',
].map(path => readFileSync(new URL(path, import.meta.url), 'utf8')).join('\n')

const publicComponents = [
  'DesignSystemProvider',
  'Icon',
  'TypeGlyph',
  'Button',
  'IconButton',
  'ButtonGroup',
  'Input',
  'TextArea',
  'FormField',
  'Checkbox',
  'Radio',
  'Switch',
  'Combobox',
  'Tag',
  'Badge',
  'Callout',
  'Tooltip',
  'Popover',
  'Menu',
  'ContextMenu',
  'Dialog',
  'Drawer',
  'Tabs',
  'Breadcrumbs',
  'AppSurface',
  'Toolbar',
  'Sidebar',
  'SplitPane',
  'Inspector',
  'PropertyList',
  'Tree',
  'EmptyState',
  'LoadingState',
  'ErrorState',
  'AccessDeniedState',
  'SignedOutState',
  'SessionExpiredState',
  'NotFoundState',
  'RateLimitedState',
  'StaleState',
  'SourceErrorState',
  'StatusBadge',
  'Kbd',
  'Avatar',
  'Skeleton',
  'CopyButton',
  'MetaRow',
  'Panel',
  'PropertyValue',
  'PropertyPanel',
  'ObjectHeader',
  'ObjectChip',
  'DataGrid',
  'LinkPanel',
  'LinkGraph',
  'SchemaGraph',
  'SearchField',
  'CommandPalette',
  'StatTile',
  'ToastProvider',
  'Pagination',
  'NavRail',
  'PageHeader',
  'FacetList',
  'ActivityFeed',
]

describe('application toolkit Storybook coverage', () => {
  for (const component of publicComponents) {
    it(`demonstrates ${component}`, () => {
      expect(storyFiles).toMatch(new RegExp(`<${component}(?:\\s|>)`))
    })
  }
})

