// Proto-derived JSON types — for backend implementers.
//
// The framework's main API (Dashboard, useDataSource, widget props)
// uses friendlier hand-rolled types from src/types/template.ts.
// Backend authors who want the exact wire shape should import these.
//
// Regenerated by `pnpm gen:proto`. Do not hand-edit src/gen/*.

export type {
  TemplateJson,
  ContextJson,
  WidgetJson,
  DataSourceJson,
  WidgetActionJson,
} from './gen/medallion/terminal/v1/template_pb.js'

export type {
  DataRequestJson,
  DataResponseJson,
  ListSourcesRequestJson,
  ListSourcesResponseJson,
  SourceJson,
  SourceParamJson,
  GenerateRequestJson,
  GenerateResponseJson,
  ActionRequestJson,
  ActionResponseJson,
  ActionWatchRequestJson,
  ActionUpdateJson,
} from './gen/medallion/terminal/v1/terminal_pb.js'

export type {
  TimeseriesPayloadJson,
  TimeseriesPointJson,
  TimeseriesSeriesJson,
  CandlePayloadJson,
  CandleJson,
  AnnotationJson,
  TablePayloadJson,
  TableColumnJson,
  MetricPayloadJson,
  GaugePayloadJson,
  GaugeBandJson,
  HeatmapPayloadJson,
  HeatmapCellJson,
  EventPayloadJson,
  EventJson,
  DistributionPayloadJson,
  DistributionSliceJson,
  TextPayloadJson,
  TextItemJson,
  OrderBookPayloadJson,
  OrderLevelJson,
  PairedGridPayloadJson,
  PairedRowJson,
  PairedSideJson,
  PairedMeasureJson,
  EmbedPayloadJson,
  AssetCatalogPayloadJson,
  AssetCatalogItemJson,
  ObjectPayloadJson,
  ObjectPropertyJson,
  ObjectLinkJson,
  ObjectActionJson,
  GraphPayloadJson,
  GraphNodeJson,
  GraphEdgeJson,
  RepositoryPayloadJson,
  RepositoryEntryJson,
  RepositoryFileJson,
  RepositoryEntryKindJson,
  RecordSetPayloadJson,
  WorkRecordJson,
  RecordFieldJson,
  RecordChoiceJson,
  RecordFieldTypeJson,
  RecordViewJson,
  RecordViewTypeJson,
  RecordSortJson,
  RecordFilterJson,
  RecordCapabilitiesJson,
  GeoPayloadJson,
  GeoFeatureJson,
} from './gen/medallion/terminal/v1/shapes_pb.js'
