// Shared Storybook fixture for every record projection. Keeping one payload
// proves that grid, board, calendar, and form are views over the same model.
export const RECORD_SET_STORY_DATA = {
  workspace_id: 'business-ops',
  table_id: 'work_items',
  table_name: 'Work items',
  primary_field: 'name',
  fields: [
    { key: 'name', label: 'Work item', type: 'RECORD_FIELD_TYPE_TEXT', required: true },
    {
      key: 'customer',
      label: 'Customer',
      type: 'RECORD_FIELD_TYPE_LINK',
      linked_table_id: 'customers',
      choices: [
        { value: 'customer-northstar', label: 'Northstar Foods' },
        { value: 'customer-harbor', label: 'Harbor & Co.' },
        { value: 'customer-beacon', label: 'Beacon Retail' },
        { value: 'customer-alder', label: 'Alder Studio' },
        { value: 'customer-summit', label: 'Summit Works' },
      ],
    },
    {
      key: 'stage',
      label: 'Stage',
      type: 'RECORD_FIELD_TYPE_SINGLE_SELECT',
      required: true,
      choices: [
        { value: 'pipeline', label: 'Pipeline', color: 'info' },
        { value: 'delivery', label: 'Delivery', color: 'info' },
        { value: 'review', label: 'Review', color: 'warn' },
        { value: 'blocked', label: 'Blocked', color: 'danger' },
        { value: 'done', label: 'Done', color: 'ok' },
      ],
    },
    {
      key: 'owner',
      label: 'Owner',
      type: 'RECORD_FIELD_TYPE_USER',
      choices: [
        { value: 'mina', label: 'Mina Patel' },
        { value: 'jules', label: 'Jules Chen' },
        { value: 'noah', label: 'Noah Williams' },
      ],
    },
    { key: 'value', label: 'Value', type: 'RECORD_FIELD_TYPE_CURRENCY', format: 'currency:USD' },
    { key: 'due_date', label: 'Due', type: 'RECORD_FIELD_TYPE_DATE' },
    {
      key: 'priority',
      label: 'Priority',
      type: 'RECORD_FIELD_TYPE_SINGLE_SELECT',
      choices: [
        { value: 'normal', label: 'Normal', color: 'info' },
        { value: 'high', label: 'High', color: 'warn' },
        { value: 'urgent', label: 'Urgent', color: 'danger' },
      ],
    },
    { key: 'completed', label: 'Complete', type: 'RECORD_FIELD_TYPE_BOOLEAN' },
    { key: 'updated_at', label: 'Updated', type: 'RECORD_FIELD_TYPE_UPDATED_AT' },
  ],
  records: [
    {
      id: 'work-101',
      revision: '3',
      updated_at: '2026-07-16T14:45:00Z',
      context: { customer_id: 'customer-northstar' },
      values: {
        name: 'Northstar onboarding',
        customer: { id: 'customer-northstar', label: 'Northstar Foods' },
        stage: 'delivery',
        owner: 'mina',
        value: 48000,
        due_date: '2026-07-18',
        priority: 'high',
        completed: false,
        updated_at: '2026-07-16T14:45:00Z',
      },
    },
    {
      id: 'work-102',
      revision: '6',
      updated_at: '2026-07-16T12:20:00Z',
      context: { customer_id: 'customer-harbor' },
      values: {
        name: 'Harbor annual renewal',
        customer: { id: 'customer-harbor', label: 'Harbor & Co.' },
        stage: 'review',
        owner: 'jules',
        value: 36000,
        due_date: '2026-07-21',
        priority: 'urgent',
        completed: false,
        updated_at: '2026-07-16T12:20:00Z',
      },
    },
    {
      id: 'work-103',
      revision: '2',
      updated_at: '2026-07-15T17:40:00Z',
      context: { customer_id: 'customer-beacon' },
      values: {
        name: 'Beacon inventory rollout',
        customer: { id: 'customer-beacon', label: 'Beacon Retail' },
        stage: 'pipeline',
        owner: 'noah',
        value: 72000,
        due_date: '2026-08-04',
        priority: 'high',
        completed: false,
        updated_at: '2026-07-15T17:40:00Z',
      },
    },
    {
      id: 'work-104',
      revision: '8',
      updated_at: '2026-07-15T20:05:00Z',
      context: { customer_id: 'customer-alder' },
      values: {
        name: 'Alder website launch',
        customer: { id: 'customer-alder', label: 'Alder Studio' },
        stage: 'done',
        owner: 'mina',
        value: 19000,
        due_date: '2026-07-15',
        priority: 'normal',
        completed: true,
        updated_at: '2026-07-15T20:05:00Z',
      },
    },
    {
      id: 'work-105',
      revision: '4',
      updated_at: '2026-07-16T15:10:00Z',
      context: { customer_id: 'customer-summit' },
      values: {
        name: 'Summit process audit',
        customer: { id: 'customer-summit', label: 'Summit Works' },
        stage: 'blocked',
        owner: 'jules',
        value: 28500,
        due_date: '2026-07-20',
        priority: 'urgent',
        completed: false,
        updated_at: '2026-07-16T15:10:00Z',
      },
    },
  ],
  views: [
    {
      id: 'all_work',
      name: 'All work',
      type: 'RECORD_VIEW_TYPE_GRID',
      visible_fields: ['name', 'customer', 'stage', 'owner', 'value', 'due_date', 'priority'],
      sorts: [{ field: 'due_date' }],
    },
    {
      id: 'active_board',
      name: 'Active delivery',
      type: 'RECORD_VIEW_TYPE_BOARD',
      visible_fields: ['customer', 'owner', 'value', 'due_date', 'priority'],
      group_by: 'stage',
      filters: [{ field: 'stage', operator: 'neq', value: 'done' }],
    },
    {
      id: 'delivery_calendar',
      name: 'Delivery calendar',
      type: 'RECORD_VIEW_TYPE_CALENDAR',
      date_field: 'due_date',
    },
    {
      id: 'intake',
      name: 'New work intake',
      type: 'RECORD_VIEW_TYPE_FORM',
      visible_fields: ['name', 'customer', 'stage', 'owner', 'value', 'due_date', 'priority'],
    },
  ],
  active_view_id: 'all_work',
  total: 5,
  capabilities: {
    create: true,
    update: true,
    delete: true,
    create_action_id: 'record_create',
    update_action_id: 'record_update',
    delete_action_id: 'record_delete',
  },
}
